version: '3.9'
services:
  elasticsearch:
    image: "elasticsearch:8.3.3"
    container_name: elasticsearch_8.3.3
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - elastic
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 5s
      timeout: 1s
      retries: 20

  sanic-app:
    image: sanic-app:latest
    build:
      context: ./sampleApp
    container_name: sanic-app
    ports:
      - "8000:8000"
    depends_on:
      elasticsearch:
        condition: service_healthy
      logstash:
        condition: service_healthy
      filebeat:
        condition: service_started
    networks:
      - elastic
    logging:
      driver: syslog
      options:
        syslog-address: tcp://host.docker.internal:9000

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.3.3
    container_name: filebeat_8.3.3
    environment:
      - setup.kibana.host=0.0.0.0:5601
    volumes:
      - "./config/filebeat.yaml:/usr/share/filebeat/filebeat.yml"
    ports:
      - "9000:9000"
    networks:
      - elastic
    depends_on:
      logstash:
        condition: service_healthy
  
  logstash:
    image: logstash:8.3.3
    container_name: logstash_8.3.3
    ports:
      - "9600:9600"
      - "5044:5044"
    depends_on:
      elasticsearch:
        condition: service_healthy
    volumes:
      - "./config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro"
    networks:
      - elastic
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9600"]
      interval: 10s
      timeout: 1s
      retries: 15

  kibana:
    image: kibana:8.3.3
    container_name: kibana_8.3.3
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - elastic

volumes:
  es_data:
    driver: local

networks:
  elastic:
    name: elastic
    driver: bridge