name: Build Docker Image

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  build:
    name: build Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: docker build ./sampleApp --file ./sampleApp/Dockerfile --tag sample-sanic-app:latest

    - name: Check env variables
      run: env
