name: Release

on:
  push:
    branches: 
       - "release/[0-9]+.[0-9]+.[0-9]+*"

jobs:

  build:
    name: Fun With GitHub Actions
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Check env variables
      run: env
      
    - name: Build Docker Image
      run: | 
        imageTag="$(echo ${GITHUB_REF_NAME} | grep -P '[0-9]+.[0-9]+.[0-9]+.*' -o)"
        docker build ./sampleApp --file ./sampleApp/Dockerfile --tag sample-sanic-app:$imageTag
